/******************************************************************************
 Auto-generated by trunk/src_plugins/map_plugins.sh - do NOT edit,
 run make map_plugins in trunk/src/ - to change any of the data below,
 edit trunk/src_plugins/PLUGIN/PLUGIN.pup
******************************************************************************/

plugin_header("\nLibrary plugins:\n")
plugin_def("lib_exp_pixmap",   "pixmap formats export lib",       sbuildin, 1)
plugin_def("lib_exp_text",     "text formats export lib",         sbuildin, 1)
plugin_def("lib_gensexpr",     "#s-expression library",           sbuildin, 1)
plugin_def("lib_gtk2_common",  "all-hid_gtk2 common code",        sdisable, 0)
plugin_def("lib_gtk4_common",  "all-hid_gtk4 common code",        sdisable, 0)
plugin_def("lib_hid_common",   "all-gui-hid common code",         sdisable, 0)
plugin_def("lib_hid_gl",       "openGL rendering",                sdisable, 0)
plugin_def("lib_portynet",     "#IPv4 tcp",                       sbuildin, 1)
plugin_def("lib_wget",         "wget(1) wrapper",                 sbuildin, 1)

plugin_header("\nFeature plugins:\n")
plugin_def("diag_rnd",         "diagnostic acts. for devs",       sbuildin, 1)
plugin_def("irc",              "on-line support (IRC)",           sbuildin, 1)
plugin_def("loghid",           "diagnostics: log HID calls",      sdisable, 1)
plugin_def("script",           "fungw turing complete scripting", sbuildin, 1)
plugin_def("stroke",           "mouse gestures",                  sbuildin, 1)

plugin_header("\nHID plugins:\n")
plugin_def("hid_batch",        "batch process (no-gui HID)",      sbuildin, 1)
plugin_def("hid_gtk2_gdk",     "GTK2 GUI, software render",       sbuildin, 1)
plugin_def("hid_gtk2_gl",      "GTK2 GUI, opengl render",         sbuildin, 1)
plugin_def("hid_gtk4_gl",      "GTK4 GUI, opengl render",         sdisable, 1)
plugin_def("hid_lesstif",      "the lesstif gui",                 sbuildin, 1)
plugin_def("hid_remote",       "remote HID server",               sdisable, 0)


plugin_dep("hid_gtk2_gdk", "lib_gtk2_common")
plugin_dep("hid_gtk2_gl", "lib_gtk2_common")
plugin_dep("hid_gtk2_gl", "lib_hid_gl")
plugin_dep("hid_gtk4_gl", "lib_gtk4_common")
plugin_dep("hid_gtk4_gl", "lib_hid_gl")
plugin_dep("hid_lesstif", "lib_hid_common")
plugin_dep("irc", "lib_portynet")
plugin_dep("lib_gtk2_common", "lib_hid_common")
plugin_dep("lib_gtk4_common", "lib_hid_common")
