action_entry(ArraySize)
action_entry(ConfRev)
action_entry(Delta)
action_entry(Desc)
action_entry(Iseq)
action_entry(Set)
action_entry(ReadOnly)
action_entry(Reset)
action_entry(Toggle)
action_entry(List)
action_entry(Load)
action_entry(Unload)
action_entry(Value)
action_entry(InhibitInc)
action_entry(InhibitDec)

