# autogenerated shell lib; intended for ringdove app packages.sh

# list of all packges
librnd_pkgs="librnd3-dev librnd3-doc librnd3-hid-gtk2-gl librnd3-cloud librnd3-lib-gui librnd3-hid-gtk2-gdk librnd3-lib-gtk librnd3-hid-lesstif librnd3 librnd3-lib-gl"

# plugin->packge mapping
librnd_plugins="
hid_gtk2_gl=librnd3-hid-gtk2-gl
hid_batch=librnd3
lib_hid_common=librnd3-lib-gui
lib_portynet=librnd3
hid_lesstif=librnd3-hid-lesstif
irc=librnd3-lib-gui
script=librnd3
hid_gtk2_gdk=librnd3-hid-gtk2-gdk
lib_gensexpr=librnd3
stroke=<NOT PACKAGED IN LIBRND>
lib_wget=librnd3-cloud
lib_hid_gl=librnd3-lib-gl
lib_gtk_common=librnd3-lib-gtk
"
