# autogenerated shell lib; intended for ringdove app packages.sh

# list of all packges
librnd_pkgs="librnd4-hid-gtk2-gdk librnd4-lib-gui librnd4-hid-lesstif librnd4-lib-gtk librnd4-pixmap librnd4-dev librnd4-hid-gtk4-gl librnd4-doc librnd4-cloud librnd4-hid-gtk2-gl librnd4-lib-gl librnd4"

# plugin=package mapping
librnd_plugins="
hid_mbtk_xlib=<NOT PACKAGED IN LIBRND>
lib_hid_common=librnd4-lib-gui
import_pixmap_gd=librnd4-pixmap
lib_gtk2_common=librnd4-lib-gtk
hid_gtk2_gdk=librnd4-hid-gtk2-gdk
lib_gensexpr=librnd4
lib_wget=librnd4-cloud
script=librnd4
hid_gtk2_gl=librnd4-hid-gtk2-gl
diag_rnd=librnd4
import_pixmap_pnm=librnd4
lib_hid_gl=librnd4-lib-gl
hid_lesstif=librnd4-hid-lesstif
hid_batch=librnd4
hid_gtk4_gl=librnd4-hid-gtk4-gl
lib_portynet=librnd4
lib_gtk4_common=librnd4-hid-gtk4-gl
lib_exp_text=librnd4
lib_exp_pixmap=librnd4-pixmap
irc=librnd4-lib-gui
"
